'''pacs'''
# photo
#python main.py --dataset PACS --method FedAVG --OOD photo --device_id 0 --csv_log --save_checkpoint &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD photo --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T1.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 1.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD photo --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.1lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.1 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD photo --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.01lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.01 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD photo --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T10.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 10.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD photo --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T5.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 5.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD photo --device_id 6 --csv_log --csv_name --save_checkpoint mu1.0 MOON.mu 1.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T1.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T0.1mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 7 --csv_log --save_checkpoint --csv_name W1.0T0.01mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T10.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T5.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD photo --device_id 0 --csv_log --csv_name mu5.0 --save_checkpoint  MOON.mu 5.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T1.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.1mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T0.01mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T10.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T5.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD photo --device_id 1 --csv_log --csv_name mu10.0  --save_checkpoint MOON.mu 10.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 7 --csv_log --save_checkpoint --csv_name W1.0T1.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.1mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.01mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T10.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD photo --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T5.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

# art_painting
#python main.py --dataset PACS --method FedAVG --OOD art_painting --device_id 0 --csv_log --save_checkpoint &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD art_painting --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T1.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 1.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD art_painting --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.1lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.1 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD art_painting --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.01lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.01 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD art_painting --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T10.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 10.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD art_painting --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T5.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 5.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD art_painting --device_id 6 --csv_log --csv_name mu1.0  --save_checkpoint MOON.mu 1.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T1.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T0.1mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 7 --csv_log --save_checkpoint --csv_name W1.0T0.01mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T10.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T5.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD art_painting --device_id 0 --csv_log --csv_name mu5.0  --save_checkpoint MOON.mu 5.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T1.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.1mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T0.01mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T10.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T5.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD art_painting --device_id 1 --csv_log --csv_name mu10.0 --save_checkpoint MOON.mu 10.0  &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 7 --csv_log --save_checkpoint --csv_name W1.0T1.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.1mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.01mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T10.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD art_painting --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T5.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

# cartoon
#python main.py --dataset PACS --method FedAVG --OOD cartoon --device_id 0 --csv_log --save_checkpoint &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD cartoon --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T1.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 1.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD cartoon --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.1lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.1 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD cartoon --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.01lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.01 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD cartoon --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T10.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 10.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD cartoon --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T5.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 5.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD cartoon --device_id 6 --csv_log --csv_name mu1.0 --save_checkpoint MOON.mu 1.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T1.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T0.1mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 7 --csv_log --save_checkpoint --csv_name W1.0T0.01mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T10.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T5.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD cartoon --device_id 0 --csv_log --csv_name mu5.0  --save_checkpoint MOON.mu 5.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T1.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.1mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T0.01mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T10.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T5.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD cartoon --device_id 1 --csv_log --csv_name mu10.0 --save_checkpoint MOON.mu 10.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 7 --csv_log --save_checkpoint --csv_name W1.0T1.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.1mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.01mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T10.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD cartoon --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T5.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

# sketch
#python main.py --dataset PACS --method FedAVG --OOD sketch --device_id 0 --csv_log --save_checkpoint &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD sketch --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T1.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 1.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD sketch --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.1lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.1 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD sketch --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.01lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.01 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD sketch --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T10.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 10.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method FedAVGCOSAddGlobal --OOD sketch --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T5.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 5.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD sketch --device_id 6 --csv_log --csv_name mu1.0 --save_checkpoint MOON.mu 1.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T1.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T0.1mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 7 --csv_log --save_checkpoint --csv_name W1.0T0.01mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T10.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T5.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD sketch --device_id 0 --csv_log --csv_name mu5.0 --save_checkpoint MOON.mu 5.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T1.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.1mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T0.01mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T10.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T5.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset PACS --method MOON --OOD sketch --device_id 1 --csv_log --csv_name mu10.0 --save_checkpoint MOON.mu 10.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 7 --csv_log --save_checkpoint --csv_name W1.0T1.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.1mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.01mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T10.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset PACS --method MOONCOSAddGlobal --OOD sketch --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T5.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
wait


'''Digits'''
# MNIST
#python main.py --dataset Digits --method FedAVG --OOD MNIST --device_id 0 --csv_log --save_checkpoint &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD MNIST --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T1.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 1.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD MNIST --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.1lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.1 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD MNIST --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.01lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.01 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD MNIST --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T10.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 10.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD MNIST --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T5.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 5.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD MNIST --device_id 6 --csv_log --csv_name mu1.0 MOON.mu 1.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T1.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.1mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.01mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T10.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T5.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD MNIST --device_id 5 --csv_log --csv_name mu5.0 MOON.mu 5.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T1.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.1mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.01mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T10.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T5.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

#python main.py --dataset Digits --method MOON --OOD MNIST --device_id 4 --csv_log --csv_name mu10.0 MOON.mu 10.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T1.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T0.1mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.01mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T10.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD MNIST --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T5.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
wait


# USPS
#python main.py --dataset Digits --method FedAVG --OOD USPS --device_id 0 --csv_log --save_checkpoint &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD USPS --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T1.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 1.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD USPS --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.1lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.1 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD USPS --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.01lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.01 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD USPS --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T10.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 10.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD USPS --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T5.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 5.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD USPS --device_id 6 --csv_log --csv_name mu1.0 MOON.mu 1.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T1.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.1mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.01mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T10.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T5.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD USPS --device_id 5 --csv_log --csv_name mu5.0 MOON.mu 5.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T1.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.1mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.01mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T10.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T5.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD USPS --device_id 4 --csv_log --csv_name mu10.0 MOON.mu 10.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T1.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T0.1mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.01mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T10.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD USPS --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T5.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
wait

# SVHN
#python main.py --dataset Digits --method FedAVG --OOD SVHN --device_id 0 --csv_log --save_checkpoint &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SVHN --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T1.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 1.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SVHN --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.1lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.1 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SVHN --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.01lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.01 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SVHN --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T10.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 10.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SVHN --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T5.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 5.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD SVHN --device_id 6 --csv_log --csv_name mu1.0 MOON.mu 1.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T1.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.1mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.01mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T10.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T5.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD SVHN --device_id 5 --csv_log --csv_name mu5.0 MOON.mu 5.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T1.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.1mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.01mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T10.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T5.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD SVHN --device_id 4 --csv_log --csv_name mu10.0 MOON.mu 10.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T1.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T0.1mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.01mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T10.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SVHN --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T5.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
wait


# SYN
#python main.py --dataset Digits --method FedAVG --OOD SYN --device_id 0 --csv_log --save_checkpoint &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SYN --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T1.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 1.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SYN --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.1lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.1 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SYN --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T0.01lr0.01_1_0 FedAVGCOSAddGlobal.temperature 0.01 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SYN --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T10.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 10.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method FedAVGCOSAddGlobal --OOD SYN --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T5.0lr0.01_1_0 FedAVGCOSAddGlobal.temperature 5.0 FedAVGCOSAddGlobal.w 1.0  FedAVGCOSAddGlobal.weight_lr 1e-2 FedAVGCOSAddGlobal.alpha 1.0 FedAVGCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD SYN --device_id 6 --csv_log --csv_name mu1.0 MOON.mu 1.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T1.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.1mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T0.01mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T10.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 4 --csv_log --save_checkpoint --csv_name W1.0T5.0mu1.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 1.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD SYN --device_id 5 --csv_log --csv_name mu5.0 MOON.mu 5.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T1.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.1mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T0.01mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T10.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 3 --csv_log --save_checkpoint --csv_name W1.0T5.0mu5.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 5.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &

python main.py --dataset Digits --method MOON --OOD SYN --device_id 4 --csv_log --csv_name mu10.0 MOON.mu 10.0 --save_checkpoint &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 5 --csv_log --save_checkpoint --csv_name W1.0T1.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 1.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 6 --csv_log --save_checkpoint --csv_name W1.0T0.1mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.1 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 0 --csv_log --save_checkpoint --csv_name W1.0T0.01mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 0.01 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 1 --csv_log --save_checkpoint --csv_name W1.0T10.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 10.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
#python main.py --dataset Digits --method MOONCOSAddGlobal --OOD SYN --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T5.0mu10.0lr0.01_1_0 MOONCOSAddGlobal.temperature 5.0 MOONCOSAddGlobal.w 1.0 MOONCOSAddGlobal.mu 10.0 MOONCOSAddGlobal.weight_lr 1e-2 MOONCOSAddGlobal.alpha 1.0 MOONCOSAddGlobal.beta 0.0 &
