python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 3 --csv_log --save_checkpoint --csv_name W0.001T1.0mu0.01lr0.01_1_0 FedProxCOSAddNHMad.w 0.001 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 1.0 FedProxCOSAddNHMad.beta 0.0 &
python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 3 --csv_log --save_checkpoint --csv_name W0.001T1.0mu0.01lr0.01_0_1 FedProxCOSAddNHMad.w 0.001 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 0.0 FedProxCOSAddNHMad.beta 1.0 &
python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 3 --csv_log --save_checkpoint --csv_name W0.001T1.0mu0.01lr0.01_1_1 FedProxCOSAddNHMad.w 0.001 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 1.0 FedProxCOSAddNHMad.beta 1.0 &

python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 0 --csv_log --save_checkpoint --csv_name W0.01T1.0mu0.01lr0.01_1_0 FedProxCOSAddNHMad.w 0.01 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 1.0 FedProxCOSAddNHMad.beta 0.0 &
python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 0 --csv_log --save_checkpoint --csv_name W0.01T1.0mu0.01lr0.01_0_1 FedProxCOSAddNHMad.w 0.01 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 0.0 FedProxCOSAddNHMad.beta 1.0 &
python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 0 --csv_log --save_checkpoint --csv_name W0.01T1.0mu0.01lr0.01_1_1 FedProxCOSAddNHMad.w 0.01 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 1.0 FedProxCOSAddNHMad.beta 1.0 &

python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 1 --csv_log --save_checkpoint --csv_name W0.1T1.0mu0.01lr0.01_1_0 FedProxCOSAddNHMad.w 0.1 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 1.0 FedProxCOSAddNHMad.beta 0.0 &
python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 1 --csv_log --save_checkpoint --csv_name W0.1T1.0mu0.01lr0.01_0_1 FedProxCOSAddNHMad.w 0.1 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 0.0 FedProxCOSAddNHMad.beta 1.0 &
python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 1 --csv_log --save_checkpoint --csv_name W0.1T1.0mu0.01lr0.01_1_1 FedProxCOSAddNHMad.w 0.1 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 1.0 FedProxCOSAddNHMad.beta 1.0 &

python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T1.0mu0.01lr0.01_1_0 FedProxCOSAddNHMad.w 1.0 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 1.0 FedProxCOSAddNHMad.beta 0.0 &
python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T1.0mu0.01lr0.01_0_1 FedProxCOSAddNHMad.w 1.0 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 0.0 FedProxCOSAddNHMad.beta 1.0 &
python main.py --dataset Digits --method FedProxCOSAddNHMad --OOD MNIST --device_id 2 --csv_log --save_checkpoint --csv_name W1.0T1.0mu0.01lr0.01_1_1 FedProxCOSAddNHMad.w 1.0 FedProxCOSAddNHMad.mu 0.01 FedProxCOSAddNHMad.weight_lr 1e-2 FedProxCOSAddNHMad.alpha 1.0 FedProxCOSAddNHMad.beta 1.0 &
